### ISSUE TITLE
Make all created editors globally available

### ISSUE THREAD

**Issue by alimony** [gsmke/django-quill#2]
It would be nice to have access to any Quill editors after they are created, for calling their methods etc.

I've solved this by creating my own app config with its own widget template that has these extra lines after instantiating the editor:

```
var editor = new QuillDjango(id, editorSelector, toolbarSelector, imageModuleOpts, theme);
window.DjangoQuillEditors = window.DjangoQuillEditors || {};
window.DjangoQuillEditors[id] = editor;
var form = document.querySelector('form');
```

Now I can get at an editor using the original element id as key:

```
var editor = window.DjangoQuillEditors.id_body.quill;
// ...do stuff with the editor object.
```

Is this feature interesting enough to include in django-quill? If so, let me know and I'll open a proper pull request for it.

**Comment by rsenk330** [comment]
This sounds like a great idea! I would definitely accept a pull request for this.
