### ISSUE TITLE
getattr(): attribute name must be string

### ISSUE THREAD

**Issue by rantecki** [gsmke/django-quill#3]
I'm trying to get a very basic example running on django 1.7.1 as per the first usage example in the README, and I get the following error:

```
TypeError at /admin/page/page/1/
getattr(): attribute name must be string
Request Method:	GET
Request URL:	http://10.0.0.3:8000/admin/page/page/1/
Django Version:	1.7.4
Exception Type:	TypeError
Exception Value:	
getattr(): attribute name must be string
Exception Location:	./env/local/lib/python2.7/site-packages/quill/widgets.py in render, line 43
```

It's dying on this line in widgets.py:

```
quill_config = getattr(quill_app, self.config)
```

If I log the value of `self.config` I get a proxy object (`<django.utils.functional.__proxy__ object at 0x3807f90>`) instead of a string as I presume is expected.

If I dump the dict of the object, I get:

```
{'_proxy____args': ('content',), '_proxy____kw': {}}
```

The proxy objects are usually used for lazy string translation, and passing it through unicode() will get the value back, but in this case the value translates to 'content' (the name of the model field) instead of 'default' as expected.

**Comment by rsenk330** [comment]
Could you please provide your model? Are you using a custom QuillConfig? Which version of django-quill are you using?

I created a simple example to test this, and was able to create and view the admin page (django-quill==0.0.2, django==1.7.4, Python 2.7.9):

**page/models.py**:
```python
from django.db import models
from quill.fields import RichTextField

class Page(models.Model):
    content = RichTextField()
    content2 = RichTextField(config='basic')
```

**page/admin.py**
```python
from django.contrib import admin
from quill.admin import QuillAdmin
from .models import Page

admin.site.register(Page, QuillAdmin)
```

The default value for the ``config`` variable is [config='default'](https://github.com/gsmke/django-quill/blob/master/quill/widgets.py#L26), which is a string. So it's interesting that it is getting transformed into a proxy object for you.

**Comment by rsenk330** [comment]
I'm closing this issue for now. Please reopen with more info if you're still having problems.
